[colors.bright]
black = "#353539"
blue = "#b9aeda"
cyan = "#f591b2"
green = "#9dc6ac"
magenta = "#ecaad6"
red = "#ffae9f"
white = "#cac9dd"
yellow = "#f0c5a9"

[colors.cursor]
cursor = "#757581"
text = "#c9c7cd"

[colors.normal]
black = "#27272a"
blue = "#aca1cf"
cyan = "#ea83a5"
green = "#90b99f"
magenta = "#e29eca"
red = "#f5a191"
white = "#c1c0d4"
yellow = "#e6b99d"

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

[env]
TERM = "xterm-256color"

[cursor]
style = "Underline"
vi_mode_style = "Block"

[font]
size = 14

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
option_as_alt = "Both"
startup_mode = "Windowed"

[window.padding]
x = 12
y = 12

[[hints.enabled]]
regex = "[0-9a-f]{40}"
mouse.enabled = true
post_processing = false
action = "Copy"
binding = { key = "H", mods = "Control|Shift"}
