[colors.bright]
black = "#353539"
blue = "#b9aeda"
cyan = "#f591b2"
green = "#9dc6ac"
magenta = "#ecaad6"
red = "#ffae9f"
white = "#cac9dd"
yellow = "#f0c5a9"

[colors.cursor]
cursor = "#757581"
text = "#c9c7cd"

[colors.normal]
black = "#27272a"
blue = "#aca1cf"
cyan = "#ea83a5"
green = "#90b99f"
magenta = "#e29eca"
red = "#f5a191"
white = "#c1c0d4"
yellow = "#e6b99d"

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
unfocused_hollow= true
thickness = 0.25 
vi_mode_style = "Block"

[cursor.style]
shape = "Underline"
blinking = "On"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[font]
size = 14

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
option_as_alt = "Both"
startup_mode = "Windowed"

[window.padding]
x = 12
y = 12

[[hints.enabled]]
regex = "[Hh][Dd][Dd][Ss]-[0-9]+"
mouse.enabled = true
post_processing = true 
command={ program = "/Users/nvadivelu/Tools/scripts/open-ozone-jira.sh" }
binding = { key = "H", mods = "Shift|Option"}

[[hints.enabled]]
regex = "#[0-9]+"
mouse.enabled = true
post_processing = true 
command={ program = "/Users/nvadivelu/Tools/scripts/open-github-pr.sh" }
binding = { key = "J", mods = "Shift|Option"}
