
# Prompt

format = """
[╭─](white)$username$hostname in $directory$package$java$python$git_branch$battery$cmd_duration
[╰──](white)$character
"""
add_newline = false
command_timeout = 500

[character]
format = "$symbol"
success_symbol = "[❯ ](bold green)"
error_symbol = "[✗ ](bold red) "
vicmd_symbol = "[❮ ](bold green)"

# Java settings
[java]
disabled = true
symbol = " "
style = "red"
format = "via [${symbol}${version}]($style) "

[hostname]
disabled = true

[username]
disabled = true

[conda]
disabled = true

[package]
disabled = true

[git_status]
disabled = true

[cmd_duration]
disabled = true

