set -g history-limit 100000

set -g default-terminal "screen-256color"

unbind %
bind '\' split-window -h

unbind '"'
bind '-' split-window -v

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'

# Configure the catppuccin plugin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'
set -ogq @catppuccin_window_text "#{window_name}"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g allow-rename off
set -g status-position bottom
set -g status-interval 5
set -g status-right-length 100
set -g status-left-length 100


set -g status-left '#{E:@catppuccin_status_session} '
set -gF  status-right "#{@catppuccin_status_directory}"

# start index at 1
set -g base-index 1
set -g pane-base-index 1

# renumber when window is closed
set -g renumber-window on
setw -g aggressive-resize off

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
